* Хатнія заданні для другога занятку (functions)

 1. *Трохкутнік*

    Напісаць функцыю, якая атрымлівае цэлы лік N і выводзіць у тэрмінал
    трохкутнік з зорачак, у ніжнім шэрагу якога іх N штук.

 2. *Каляровы тэкст*

    Напісаць функцыю, якая атрымлівае тэкст і выводзіць у тэрмінал гэты
    ж тэкст, толькі кожнае слова ў ім падсвечана выпадковым колерам.

 3. Напісаць функцыю, якая атрымлівае тэкст і вяртае слоўнік, у якім
    ключы ёсць словамі з тэксту, а значэннямі - чашчыня, з якой слова
    сустракаецца ў тэксце.

 4. *Прывітанне*

    Напісаць функцыю, якая атрымлівае код мовы (напрыклад en, be, ru,
    ua, fr, de), а вяртае прывітанне на гэтай мове.

 5. *Ромб*

    Напісаць функцыю, якая атрымлівае цэлы лік N і выводзіць ромб з
    зорачак, у цэнтральным шэрагу якога іх N штук.

 6. *Simple text wrap*

    Напісаць функцыю, якая атрымлівае тэкст і максімальную даўжыню радка,
    разбівае яго на радкі не даўжэй за максімальну даўжыню і не разрываючы
    словаў, і вяртае выніковы тэкст. Мова на выбар распрацоўніка.

 7. *Slugify*

    Напісаць функцыю, якая атрымлівае загаловак артыкулу і вяртае
    slug-радок. Slugify - гэта пераўтварэнне любога загалоўка ў
    акуратны радок для выкарыстання ў адрасе артыкула. Напрыклад:
    human-readable-url-slugs-from-any-string

 8. *Фармат колеру*

    Напісаць функцыю, якая атрымлівае колер у фарматах: назва, rgb, hex,
    а вяртае яго ж у фармаце rgb.

 9. *Функцыянальнае прывітанне*

    Напісаць функцыю, якая атрымлівае код мовы (напрыклад en, be, ru,
    ua, fr, de), а вяртае ФУНКЦЫЮ, якая будзе вяртаць прывітанне на
    гэтай мове.

 10. *Text wrap*

    Напісаць функцыю, якая атрымлівае тэкст і максімальную даўжыню радка,
    правільна разбівае яго на радкі з пераносамі словаў у канцы радкоў,
    калі яны патрэбны, і вяртае вынік. Мова на выбар распрацоўніка.

 11. *Параўнанне*

    Напісаць функцыю, якая атрымлівае два радкі і выводзіць у тэрмінал
    іх розніцу.

 12. *Conway*

    Напісаць функцыю, якая атрымлівае двухмерную матрыцу Conway's Game
    of Life, якая складаецца з адзінак і нулей (alive і dead) і вяртае
    наступнае пакаленне. Поле бясконцае, то бок краі поля празрыстыя.
