* Домашние задачи для первого занятия (intro)


** Уровень 1

*** No math

 1. *Меньшее из трех.*
    Пользователь вводит три числа.
    Программа должна вывести на экран наименьшее из них.

 2. *Обмен значений.*
    Как поменять местами содержимое переменных A и B?
    Покажите, как можно это сделать.

 3. *Перевод времени.*
    Написать программу, которая выполняет следующие операции:
    Пользователь вводит некоторое число секунд.
    Программа показывает пересчитывает это число в часы, минуты, секунды 
    и выводит на экран.

*** Math

  1. *Ровно одно.*
     Даны два целых числа: A, B. 
     Проверить истинность высказывания: «Ровно одно из чисел A и B нечетное».

  2. *Площади.*
     Даны два круга с общим центром и радиусами R1 и R2 (R1 > R2).
     Найти площади этих кругов S1 и S2, а также площадь S3 кольца,
     внешний радиус которого равен R1, а внутренний радиус равен R2.

  3. *Сумма ряда.*
    Дано целое число N (N > 0). Найти сумму

    1 + 1/(1!) + 1/(2!) + 1/(3!) + ... + 1/(N!)

    (выражение N! — N–факториал — обозначает произведение всех целых
    чисел от 1 до N: N! = 1·2·...·N).


** Уровень 2

*** No math

  1. *Зодиак*
     Написать программу, которая способную определять знак зодиака
     для даты, введенной пользователем, в виде двух чисел: дня и месяца.

     В ответ программа выводит знак Зодиака, соответствующий этой дате:
     «Водолей» (20.1–18.2),
     «Рыбы» (19.2–20.3),
     «Овен» (21.3–19.4),
     «Телец» (20.4–20.5),
     «Близнецы» (21.5–21.6),
     «Рак» (22.6–22.7),
     «Лев» (23.7–22.8),
     «Дева» (23.8–22.9),
     «Весы» (23.9–22.10),
     «Скорпион» (23.10–22.11),
     «Стрелец» (23.11–21.12),
     «Козерог» (22.12–19.1).

    Не забудьте предусмотреть проверку правильности даты!

  2. *Игра «Кости»*
     Написать интерактивную программу, которая эмулирует игру в кости.

     Перед началом каждого раунда игры пользователь может сделать ставку и
     указать число от одного до двенадцати (как на паре игральных кубиков).

     После этого компьютер бросает кости (с использованием случайных чисел) и 
     сравнивает полученный результат со значением, указанным пользователем 
     в начале раунда.

     Если выпавшее на кубиках число совпало с числом, указанным пользователем,
     то на его счет перечисляется сумма удвоенной ставки, иначе с его счета 
     снимается одна ставка.

     Программа выводит текущий счет пользователя и предлагает ему повторить игру 
     либо выйти.


*** Math

 1. *Прямоугольник.*
    Даны целочисленные координаты трех вершин прямоугольника, стороны
    которого параллельны координатным осям. Найти координаты его
    четвертой вершины.

 2. *Сумма ряда 2.*
    Дано вещественное число A и целое число N (> 0). Используя один цикл,
    найти значение выражения

    1 – A + A^2 – A^3 + ... + (–1)·N·A^N
    
    без использования условного оператора.

 3. *Разные элементы*
    Дан набор из N целых чисел, упорядоченный по возрастанию.
    Данный набор может содержать одинаковые элементы. 
    Вывести в том же порядке все различные элементы данного набора.

** Уровень 3

 1. *Пилообразность.* 
    Дано целое число N (> 2) и набор из N вещественных чисел. Набор
    называется пилообразным, если каждый его внутренний элемент либо
    больше, либо меньше обоих своих соседей (то есть является «зубцом»).
    Если данный набор является пилообразным, то вывести 0; в противном
    случае вывести номер первого элемента, не являющегося зубцом.

 2. *10001-ое простое число* (http://euler.jakumo.org/problems/view/7.html).

    Выписав первые шесть простых чисел, получим 2, 3, 5, 7, 11 и 13.
    Очевидно, что 6-ое простое число - 13. 
    Какое число является 10001-ым простым числом?

 3. *Гипотеза Коллатца* (http://euler.jakumo.org/problems/view/14.html).
    Следующая повторяющаяся последовательность определена для множества натуральных чисел:

    n → n/2 (n - чётное)
    n → 3n + 1 (n - нечётное)
    
    Используя описанное выше правило и начиная с 13, сгенерируется следующая последовательность:

    13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1

    Получившаяся последовательность (начиная с 13 и заканчивая 1) содержит 10 элементов.
    Хотя это до сих пор и не доказано (проблема Коллатца (Collatz)), предполагается,
    что все сгенерированные таким образом последовательности оканчиваются 1.

    Какой начальный элемент меньше миллиона генерирует самую длинную последовательность?
